spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/gestiondestock?createDatabaseIfNotExist=true&createTablesIfNotExist=true&userSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: "02011213"
    driver-class-name: com.mysql.jdbc.Driver
  ## Specify DBMS
  jpa:
    database: MYSQL
    show-sql: false
    properties:
      hibernate:
        session_factory:
          interceptor: com.amine.gestiondestock.interceptor.Interceptor


    # Hibernate DDL Auto (create, create-drop, update)
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5Dialect

#application:
#  security:
#    jwt:
#      secret-key: my-secret-key

server:
  port: 8081

