spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/gestiondestock?createDatabaseIfNotExist=true&createTablesIfNotExist=true&userSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: "02011213"
    driver-class-name: com.mysql.jdbc.Driver
  ## Specify DBMS
  jpa:
    database: MYSQL
    show-sql: false
    properties:
      hibernate:
        session_factory:
          interceptor: com.amine.gestiondestock.interceptor.Interceptor


    # Hibernate DDL Auto (create, create-drop, update)
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5Dialect

flickr:
  apiKey: d64a92ac5d1527ec1ffbdffad053b8b0
  apiSecret: 3a8c52a2d8c4afe2
  appKey: 72157720889966587-f14f644fa37dd814
  appSecret: 3055845ea9e0901e


server:
  port: 8081

